sudo: required
services:
  - docker 

before_install:
  - docker build -t docker-react-stan -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-stan npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-147287935329"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
